// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6DEs2RlIn5tHbQHBEaHVVNvQavwA1-0',
    appId: '1:142442437372:web:03ac0372b4442302099579',
    messagingSenderId: '142442437372',
    projectId: 'todo-6bf5f',
    authDomain: 'todo-6bf5f.firebaseapp.com',
    storageBucket: 'todo-6bf5f.appspot.com',
    measurementId: 'G-1M7PDRM0XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-tDSt4rad70eetFvkA6TvQYuF0uDhu44',
    appId: '1:142442437372:android:78f3535aa56f9d7b099579',
    messagingSenderId: '142442437372',
    projectId: 'todo-6bf5f',
    storageBucket: 'todo-6bf5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeNDsPnAFAGXYIiL5Oy4U_X6kqLG2vgYc',
    appId: '1:142442437372:ios:ba270c70c08974e3099579',
    messagingSenderId: '142442437372',
    projectId: 'todo-6bf5f',
    storageBucket: 'todo-6bf5f.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeNDsPnAFAGXYIiL5Oy4U_X6kqLG2vgYc',
    appId: '1:142442437372:ios:ba270c70c08974e3099579',
    messagingSenderId: '142442437372',
    projectId: 'todo-6bf5f',
    storageBucket: 'todo-6bf5f.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc6DEs2RlIn5tHbQHBEaHVVNvQavwA1-0',
    appId: '1:142442437372:web:761e70e98bd2a8a2099579',
    messagingSenderId: '142442437372',
    projectId: 'todo-6bf5f',
    authDomain: 'todo-6bf5f.firebaseapp.com',
    storageBucket: 'todo-6bf5f.appspot.com',
    measurementId: 'G-ND08KT0L5E',
  );
}
